name: mariadb

on: [push, pull_request]

jobs:
  mariadb:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_USER: knex
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: fastify_session
          MYSQL_ROOT_PASSWORD: root_password
        # Set health checks to wait until postgres has started
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10
        

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn build
      - run: yarn test
        env:
          CI: true
          DATABASE_URL: mysql://knex:password@localhost:3306/fastify_session?debug=true&charset=utf8
          DATABASE_CLIENT: mysql2
      - run: yarn run lint