name: sqlite

on: [push, pull_request]

jobs:
  sqlitetest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn add sqlite3
      - run: ./node_modules/.bin/knex migrate:latest
        env:
          NODE_ENV: sqlite3
      - run: yarn build
      - run: yarn test
        env:
          CI: true
          DATABASE_URL: "./unleashsql.sqlite"
          DATABASE_CLIENT: "sqlite3"
      - run: yarn run lint